services:
  - type: web
    env: node # env: docker for larger monorepos
    name: fh-prod-backend1
    repo: https://github.com/DavidKielty1/TurboRepoFormHub.git
    plan: free
    buildFilter:
      paths:
        - apps/backend/**
    buildCommand: pnpm i && npx prisma generate && npm run build
    startCommand: cd apps/backend; pnpm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          type: database
          name: fh-prod-db1
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fh-prod-redis1
          property: connectionString

  - type: web
    env: static
    name: fh-prob-frontend1
    repo: https://github.com/DavidKielty1/TurboRepoFormHub.git
    buildFilter:
      paths:
        - apps/frontend/**
    buildCommand: pnpm i && pnpm run build --filter=frontend
    staticPublishPath: ./apps/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_GRAPHQL_HOST
        fromService:
          type: web
          name: fh-prob-frontend1
          property: host

  - type: redis
    name: fh-prod-redis1
    plan: free
    ipAllowList: []

databases:
  - name: fh-prod-db1
    plan: free
